// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:610b220a-a80a-4765-9f60-2e2da2c075fc",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_jvmvqZbNP",
    "aws_user_pools_web_client_id": "4jqfrhk8hop4ti6pp144haenb6",
    "oauth": {
        "domain": "contestsitegodcbd831c0-cbd831c0-test.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://contextsite.com/login/",
        "redirectSignOut": "https://contextsite.com/logout/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_content_delivery_bucket": "contestsitegod-20200109174043-hostingbucket-test",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "http://contestsitegod-20200109174043-hostingbucket-test.s3-website-us-east-1.amazonaws.com",
    "aws_user_files_s3_bucket": "bucketsite92047-test",
    "aws_user_files_s3_bucket_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://jc5w5x4clndtrbefhlg4fuqo74.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-45ybmj7mlbee3karqm474pkni4"
};


export default awsmobile;
