// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:65a1d9b5-71c7-4268-97f8-2d26d1a88f21",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_X7vTWrIQw",
    "aws_user_pools_web_client_id": "7e1fbakq8a5vusmtms9qa4j2vf",
    "oauth": {
        "domain": "contestsitegodcbd831c0-cbd831c0-production.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://contextsite.com/login/",
        "redirectSignOut": "https://contextsite.com/logout/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_content_delivery_bucket": "contestsitegod-20200109174043-hostingbucket-production",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "http://contestsitegod-20200109174043-hostingbucket-production.s3-website-us-east-1.amazonaws.com",
    "aws_user_files_s3_bucket": "bucketsite103550-production",
    "aws_user_files_s3_bucket_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://4s2jehyum5cl7om2zqaynkg3bm.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-cfgh3xayyrfydcvzsrzunljuda",
    "aws_mobile_analytics_app_id": "b2cdd120434641af9df30413c6496dfe",
    "aws_mobile_analytics_app_region": "us-east-1"
};


export default awsmobile;
